### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by fatso83** [fatso83/QValues#1]
@davetransom: mind if I add a license so that it is clear that people can actually use the code, even though you already said so?

**Comment by davetransom** [comment]
sure @fatso83, I went with MIT for my other repos => https://github.com/csharpvitamins/CSharpVitamins.Tabulation/blob/master/LICENSE.md

**Comment by fatso83** [comment]
Great, thank you! It's already [found its use for me](https://github.com/Geta/SEO.Sitemaps/pull/39), so thanks for article and the code! Let's hope it can be useful for others.

And I fixed an i18n bug in the code as well when it comes to float parsing 🤓
